DEBUG 2023-08-22 16:50:57,489 base Asynchronous middleware Agronomy.middleware.PreventGoogleOauthMiddleware adapted.
DEBUG 2023-08-22 16:50:57,981 autoreload File C:\Users\Asif\PycharmProjects\Capstone\Agronomy\Agronomy\asgi.py first seen with mtime 1691481354.5409446
DEBUG 2023-08-22 16:50:57,985 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\generic\__init__.py first seen with mtime 1691220504.6124601
DEBUG 2023-08-22 16:50:57,987 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\middleware.py first seen with mtime 1691220504.6054785
DEBUG 2023-08-22 16:50:57,999 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\security\__init__.py first seen with mtime 1691220504.6194408
DEBUG 2023-08-22 16:50:58,006 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\auth.py first seen with mtime 1691220504.5984979
DEBUG 2023-08-22 16:50:58,007 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\sessions.py first seen with mtime 1691220504.6074731
DEBUG 2023-08-22 16:50:58,021 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\generic\websocket.py first seen with mtime 1691220504.6144545
DEBUG 2023-08-22 16:50:58,023 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py first seen with mtime 1692556069.547395
DEBUG 2023-08-22 16:50:58,035 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\security\websocket.py first seen with mtime 1691220504.620438
DEBUG 2023-08-22 16:50:58,038 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\db.py first seen with mtime 1691220504.6004913
DEBUG 2023-08-22 16:50:58,047 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\consumer.py first seen with mtime 1691220504.599516
DEBUG 2023-08-22 16:50:59,526 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\utils.py first seen with mtime 1691220504.6104648
DEBUG 2023-08-22 16:50:59,527 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\createable_api_resource.py first seen with mtime 1690721537.8743556
DEBUG 2023-08-22 16:50:59,527 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\version.py first seen with mtime 1690721537.8574007
DEBUG 2023-08-22 16:50:59,530 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\file.py first seen with mtime 1690721537.868371
DEBUG 2023-08-22 16:50:59,531 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\__init__.py first seen with mtime 1690721537.859395
DEBUG 2023-08-22 16:50:59,531 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\base_protocol.py first seen with mtime 1690721537.4754877
DEBUG 2023-08-22 16:50:59,531 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\yarl\_quoting.py first seen with mtime 1690721537.3814409
DEBUG 2023-08-22 16:50:59,532 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\yarl\_url.py first seen with mtime 1690721537.386458
DEBUG 2023-08-22 16:50:59,533 autoreload File C:\Program Files\Python\Python311\Lib\pydoc.py first seen with mtime 1680631450.0
DEBUG 2023-08-22 16:50:59,533 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\payload_streamer.py first seen with mtime 1690721537.4933436
DEBUG 2023-08-22 16:50:59,534 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\http_parser.py first seen with mtime 1690721537.486486
DEBUG 2023-08-22 16:50:59,534 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\customer.py first seen with mtime 1690721537.8623867
DEBUG 2023-08-22 16:50:59,535 autoreload File C:\Users\Asif\PycharmProjects\Capstone\Agronomy\pages\consumers.py first seen with mtime 1691467837.4324281
DEBUG 2023-08-22 16:50:59,536 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\fine_tune.py first seen with mtime 1690721537.868371
DEBUG 2023-08-22 16:50:59,537 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py first seen with mtime 1692556068.7605233
DEBUG 2023-08-22 16:50:59,537 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\abc.py first seen with mtime 1690721537.4745162
DEBUG 2023-08-22 16:50:59,538 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\frozenlist\__init__.py first seen with mtime 1690721537.318274
DEBUG 2023-08-22 16:50:59,538 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\embedding.py first seen with mtime 1690721537.865379
DEBUG 2023-08-22 16:50:59,541 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\multidict\__init__.py first seen with mtime 1690721537.2653832
DEBUG 2023-08-22 16:50:59,541 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\cookiejar.py first seen with mtime 1690721537.4815056
DEBUG 2023-08-22 16:50:59,542 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\helpers.py first seen with mtime 1690721537.4834847
DEBUG 2023-08-22 16:50:59,543 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\datalib\common.py first seen with mtime 1690721537.8823335
DEBUG 2023-08-22 16:50:59,544 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\listable_api_resource.py first seen with mtime 1690721537.877347
DEBUG 2023-08-22 16:50:59,545 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\deletable_api_resource.py first seen with mtime 1690721537.8753521
DEBUG 2023-08-22 16:50:59,547 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py first seen with mtime 1690721537.8763494
DEBUG 2023-08-22 16:50:59,548 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\multidict\_multidict.cp311-win_amd64.pyd first seen with mtime 1690721537.269372
DEBUG 2023-08-22 16:50:59,549 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_requestor.py first seen with mtime 1690721537.8484242
DEBUG 2023-08-22 16:50:59,551 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\completion.py first seen with mtime 1690721537.8623867
DEBUG 2023-08-22 16:50:59,552 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\tracing.py first seen with mtime 1690721537.4983304
DEBUG 2023-08-22 16:50:59,553 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\http_writer.py first seen with mtime 1690721537.4880452
DEBUG 2023-08-22 16:50:59,553 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\datalib\__init__.py first seen with mtime 1690721537.8813362
DEBUG 2023-08-22 16:50:59,555 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\core\asgi.py first seen with mtime 1692556069.3349617
DEBUG 2023-08-22 16:50:59,558 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\middleware\clickjacking.py first seen with mtime 1692556069.7199316
DEBUG 2023-08-22 16:50:59,559 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\formdata.py first seen with mtime 1690721537.482469
DEBUG 2023-08-22 16:50:59,560 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\image.py first seen with mtime 1690721537.8693686
DEBUG 2023-08-22 16:50:59,561 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\async_timeout\__init__.py first seen with mtime 1690721537.351186
DEBUG 2023-08-22 16:50:59,562 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\_http_writer.cp311-win_amd64.pyd first seen with mtime 1690721537.4705012
DEBUG 2023-08-22 16:50:59,563 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\edit.py first seen with mtime 1690721537.864382
DEBUG 2023-08-22 16:50:59,563 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\locks.py first seen with mtime 1690721537.4890451
DEBUG 2023-08-22 16:50:59,565 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\error_object.py first seen with mtime 1690721537.8673735
DEBUG 2023-08-22 16:50:59,566 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\moderation.py first seen with mtime 1690721537.871363
DEBUG 2023-08-22 16:50:59,568 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\openai_object.py first seen with mtime 1690721537.8524137
DEBUG 2023-08-22 16:50:59,568 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiosignal\__init__.py first seen with mtime 1690721537.4323263
DEBUG 2023-08-22 16:50:59,569 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\multidict\_abc.py first seen with mtime 1690721537.2673833
DEBUG 2023-08-22 16:50:59,571 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\nested_resource_class_methods.py first seen with mtime 1690721537.878344
DEBUG 2023-08-22 16:50:59,571 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\util.py first seen with mtime 1690721537.855406
DEBUG 2023-08-22 16:50:59,572 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\client_ws.py first seen with mtime 1690721537.4795065
DEBUG 2023-08-22 16:50:59,572 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\client_proto.py first seen with mtime 1690721537.4774823
DEBUG 2023-08-22 16:50:59,573 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\typedefs.py first seen with mtime 1690721537.499328
DEBUG 2023-08-22 16:50:59,574 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\tcp_helpers.py first seen with mtime 1690721537.4973328
DEBUG 2023-08-22 16:50:59,574 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\client_exceptions.py first seen with mtime 1690721537.4765122
DEBUG 2023-08-22 16:50:59,575 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\resolver.py first seen with mtime 1690721537.4953382
DEBUG 2023-08-22 16:50:59,575 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\__init__.py first seen with mtime 1690721537.8723605
DEBUG 2023-08-22 16:50:59,577 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\openai_response.py first seen with mtime 1690721537.853411
DEBUG 2023-08-22 16:50:59,577 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\yarl\_quoting_c.cp311-win_amd64.pyd first seen with mtime 1690721537.382459
DEBUG 2023-08-22 16:50:59,577 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\engine.py first seen with mtime 1690721537.8663764
DEBUG 2023-08-22 16:50:59,578 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\payload.py first seen with mtime 1690721537.4913487
DEBUG 2023-08-22 16:50:59,580 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\audio.py first seen with mtime 1690721537.860392
DEBUG 2023-08-22 16:50:59,581 autoreload File C:\Users\Asif\PycharmProjects\Capstone\Agronomy\Agronomy\routing.py first seen with mtime 1691477771.0502408
DEBUG 2023-08-22 16:50:59,583 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\__init__.py first seen with mtime 1690721537.4602573
DEBUG 2023-08-22 16:50:59,586 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\_websocket.cp311-win_amd64.pyd first seen with mtime 1690721537.472528
DEBUG 2023-08-22 16:50:59,586 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\streams.py first seen with mtime 1690721537.4963357
DEBUG 2023-08-22 16:50:59,587 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py first seen with mtime 1690721537.487723
DEBUG 2023-08-22 16:50:59,587 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\deployment.py first seen with mtime 1690721537.8633842
DEBUG 2023-08-22 16:50:59,587 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py first seen with mtime 1690721537.8613896
DEBUG 2023-08-22 16:50:59,588 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\hdrs.py first seen with mtime 1690721537.482469
DEBUG 2023-08-22 16:50:59,589 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\log.py first seen with mtime 1690721537.4903498
DEBUG 2023-08-22 16:50:59,589 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\_helpers.cp311-win_amd64.pyd first seen with mtime 1690721537.464246
DEBUG 2023-08-22 16:50:59,590 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\error.py first seen with mtime 1690721537.8504188
DEBUG 2023-08-22 16:50:59,591 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\client.py first seen with mtime 1690721537.4765122
DEBUG 2023-08-22 16:50:59,591 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\multidict\_multidict_base.py first seen with mtime 1690721537.271346
DEBUG 2023-08-22 16:50:59,594 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\__init__.py first seen with mtime 1690721537.8464296
DEBUG 2023-08-22 16:50:59,596 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\api_resource.py first seen with mtime 1690721537.873358
DEBUG 2023-08-22 16:50:59,598 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py first seen with mtime 1690721537.4785063
DEBUG 2023-08-22 16:50:59,598 autoreload File C:\Users\Asif\AppData\Roaming\Python\Python311\site-packages\channels\layers.py first seen with mtime 1691220504.6044812
DEBUG 2023-08-22 16:50:59,598 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\_http_parser.cp311-win_amd64.pyd first seen with mtime 1690721537.4685082
DEBUG 2023-08-22 16:50:59,598 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\frozenlist\_frozenlist.cp311-win_amd64.pyd first seen with mtime 1690721537.3202689
DEBUG 2023-08-22 16:50:59,600 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\model.py first seen with mtime 1690721537.870366
DEBUG 2023-08-22 16:50:59,600 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\connector.py first seen with mtime 1690721537.4804745
DEBUG 2023-08-22 16:50:59,601 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\multipart.py first seen with mtime 1690721537.4913487
DEBUG 2023-08-22 16:50:59,602 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\datalib\numpy_helper.py first seen with mtime 1690721537.8833308
DEBUG 2023-08-22 16:50:59,603 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\multidict\_compat.py first seen with mtime 1690721537.268353
DEBUG 2023-08-22 16:50:59,603 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\yarl\__init__.py first seen with mtime 1690721537.3804715
DEBUG 2023-08-22 16:50:59,603 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\http.py first seen with mtime 1690721537.4844913
DEBUG 2023-08-22 16:50:59,604 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\aiohttp\http_exceptions.py first seen with mtime 1690721537.4854617
DEBUG 2023-08-22 16:50:59,605 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\openai\api_resources\abstract\updateable_api_resource.py first seen with mtime 1690721537.8793418
DEBUG 2023-08-22 16:51:01,399 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 51, 1, 396254), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 51, 1, 396254), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:51:01,630 utils (0.015) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:51:01,855 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:51:02,077 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_problem"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:51:02,265 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\storage\fallback.py first seen with mtime 1692556068.3306785
DEBUG 2023-08-22 16:51:02,266 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\storage\base.py first seen with mtime 1692556068.3286834
DEBUG 2023-08-22 16:51:02,276 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\sessions\serializers.py first seen with mtime 1692556068.756511
DEBUG 2023-08-22 16:51:02,283 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\storage\cookie.py first seen with mtime 1692556068.3296804
DEBUG 2023-08-22 16:51:02,288 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\storage\session.py first seen with mtime 1692556068.3306785
DEBUG 2023-08-22 16:51:02,298 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_room"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:51:02,304 autoreload File C:\Users\Asif\PycharmProjects\Capstone\Agronomy\accounts\backends.py first seen with mtime 1692267196.4394486
DEBUG 2023-08-22 16:51:02,315 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\utils.py first seen with mtime 1692556068.3256903
DEBUG 2023-08-22 16:51:02,552 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:51:02,772 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:51:02,998 runserver HTTP GET /requests/expert 200 [1.61, 127.0.0.1:56548]
DEBUG 2023-08-22 16:51:03,085 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 51, 3, 81998), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 51, 3, 81998), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:51:03,891 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\auth\context_processors.py first seen with mtime 1692556066.904357
DEBUG 2023-08-22 16:51:03,897 autoreload File C:\Users\Asif\PycharmProjects\Capstone\Agronomy\Agronomy\context_processors.py first seen with mtime 1692678125.990366
DEBUG 2023-08-22 16:51:03,921 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\template\context_processors.py first seen with mtime 1692556069.7328992
DEBUG 2023-08-22 16:51:03,950 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\contrib\messages\context_processors.py first seen with mtime 1692556068.3226979
DEBUG 2023-08-22 16:51:04,437 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:51:05,599 runserver HTTP GET /media/default/default_profile_img.png 200 [2.52, 127.0.0.1:56548]
DEBUG 2023-08-22 16:52:46,663 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 52, 46, 661481), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 52, 46, 661481), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:52:48,815 utils (0.016) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:52:49,041 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:52:49,264 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_problem"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:52:49,489 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_room"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:52:49,734 utils (0.016) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:52:49,964 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:52:50,188 runserver HTTP GET /requests/expert 200 [3.53, 127.0.0.1:56620]
DEBUG 2023-08-22 16:52:57,806 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 52, 57, 805518), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 52, 57, 805518), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:52:59,861 utils (0.016) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:00,103 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:00,330 utils (0.015) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:53:00,554 runserver HTTP GET /testimonials 200 [2.75, 127.0.0.1:56620]
DEBUG 2023-08-22 16:53:04,092 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 53, 4, 90531), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 53, 4, 90531), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:53:06,149 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:06,391 utils (0.016) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:06,617 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:53:06,844 runserver HTTP GET /weather 200 [2.75, 127.0.0.1:56620]
DEBUG 2023-08-22 16:53:11,485 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 53, 11, 483453), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 53, 11, 483453), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:53:13,649 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:14,509 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:14,743 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:53:14,974 runserver HTTP POST /weather 200 [3.49, 127.0.0.1:56620]
DEBUG 2023-08-22 16:53:16,090 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\conf\locale\bn\formats.py first seen with mtime 1692556065.8333466
DEBUG 2023-08-22 16:53:16,111 autoreload File C:\Program Files\Python\Python311\Lib\site-packages\django\conf\locale\bn\__init__.py first seen with mtime 1692556065.8323493
DEBUG 2023-08-22 16:53:25,902 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 53, 25, 900409), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 53, 25, 900409), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:53:28,001 utils (0.015) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:28,229 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_question"' - PARAMS = (); args=(); alias=default
DEBUG 2023-08-22 16:53:28,472 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:28,694 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:28,920 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,927 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,929 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,931 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,933 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,934 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,935 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,936 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,937 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
DEBUG 2023-08-22 16:53:28,938 base Exception while resolving variable 'tab' in template 'questions.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QueryDict' object has no attribute 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [tab] in <QueryDict: {}>
INFO 2023-08-22 16:53:28,946 runserver HTTP GET /questions 200 [3.05, 127.0.0.1:56620]
DEBUG 2023-08-22 16:53:47,958 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 53, 47, 955092), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 53, 47, 955092), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:53:50,093 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:50,334 utils (0.015) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:50,558 utils (0.000) QUERY = 'SELECT "pages_problem"."id", "pages_problem"."created", "pages_problem"."last_modified", "pages_problem"."account_id", "pages_problem"."title", "pages_problem"."tags" FROM "pages_problem" WHERE "pages_problem"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:50,787 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:51,008 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:53:51,229 base Exception while resolving variable 'case' in template 'chat/chat-expert.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [case] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D43681760>>, 'request': <ASGIRequest: GET '/chat/expert'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/expert'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'problems': [], 'problems_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: content. Contents: [<TextNode: '\n\n    <section class="py-'>, <IncludeNode: template=<FilterExpression "'message.html'">>, <TextNode: '\n            <div class="'>, <URLNode view_name=''request-expert'' args=[] kwargs={} as=None>, <TextNode: '">New chat</a>\n          '>, <IfNode>, <TextNode: '\n                    </di'>, <IfNode>, <TextNode: '\n                </div>\n '>]>}]
DEBUG 2023-08-22 16:53:51,235 base Exception while resolving variable 'ws_url' in template 'chat/chat-expert.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [ws_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D43681760>>, 'request': <ASGIRequest: GET '/chat/expert'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/expert'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'problems': [], 'problems_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: script. Contents: [<TextNode: '\n\n    <script src="https:'>, <Variable Node: DATA_UPLOAD_MAX_MEMORY_SIZE>, <TextNode: ';\n\n    </script>\n\n    <sc'>, StaticNode(varname=None, path=<FilterExpression '"assets/js/form_handler.js"'>), <TextNode: '"></script>\n\n    <script '>, <Variable Node: ws_url>, <TextNode: '";\n        if (wsURL !== '>, <Variable Node: request.user.id>, <TextNode: '";\n                    di'>]>}]
INFO 2023-08-22 16:53:51,240 runserver HTTP GET /chat/expert 200 [3.29, 127.0.0.1:56620]
DEBUG 2023-08-22 16:54:13,751 utils (0.015) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 54, 13, 749321), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 54, 13, 749321), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:54:16,322 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:16,561 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:16,784 utils (0.000) QUERY = 'SELECT COUNT(*) AS "__count" FROM "pages_room" WHERE "pages_room"."expert_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:17,015 utils (0.016) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:17,241 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:17,473 utils (0.016) QUERY = 'SELECT "pages_room"."id", "pages_room"."created", "pages_room"."last_modified", "pages_room"."problem_id", "pages_room"."user_id", "pages_room"."expert_id", "pages_room"."ai", "pages_room"."assigned" FROM "pages_room" WHERE "pages_room"."expert_id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:17,464 base Exception while resolving variable 'case' in template 'chat/chat-user.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [case] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D4364B740>>, 'request': <ASGIRequest: GET '/chat/user'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/user'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'expert_rooms': <QuerySet []>, 'expert_rooms_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: content. Contents: [<TextNode: '\n\n    <section class="py-'>, <IncludeNode: template=<FilterExpression "'message.html'">>, <TextNode: '\n            <div class="'>, <URLNode view_name=''request-expert'' args=[] kwargs={} as=None>, <TextNode: '">New chat</a>\n          '>, <IfNode>, <TextNode: '\n                    </di'>, <IfNode>, <TextNode: '\n                </div>\n '>]>}]
DEBUG 2023-08-22 16:54:17,712 utils (0.000) QUERY = 'SELECT "pages_room"."id", "pages_room"."created", "pages_room"."last_modified", "pages_room"."problem_id", "pages_room"."user_id", "pages_room"."expert_id", "pages_room"."ai", "pages_room"."assigned" FROM "pages_room" WHERE "pages_room"."expert_id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:17,703 base Exception while resolving variable 'ws_url' in template 'chat/chat-user.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [ws_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D4364B740>>, 'request': <ASGIRequest: GET '/chat/user'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/user'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'expert_rooms': <QuerySet []>, 'expert_rooms_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: script. Contents: [<TextNode: '\n\n    <script src="https:'>, <Variable Node: DATA_UPLOAD_MAX_MEMORY_SIZE>, <TextNode: ';\n\n    </script>\n\n    <sc'>, StaticNode(varname=None, path=<FilterExpression '"assets/js/form_handler.js"'>), <TextNode: '"></script>\n\n    <script '>, <Variable Node: ws_url>, <TextNode: '";\n        if (wsURL !== '>, <Variable Node: request.user.id>, <TextNode: '";\n                    di'>]>}]
INFO 2023-08-22 16:54:17,942 runserver HTTP GET /chat/user 200 [4.19, 127.0.0.1:56620]
DEBUG 2023-08-22 16:54:21,125 utils (0.015) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 54, 21, 123758), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 54, 21, 123758), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:54:23,846 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:24,087 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:24,321 utils (0.000) QUERY = 'SELECT "pages_problem"."id", "pages_problem"."created", "pages_problem"."last_modified", "pages_problem"."account_id", "pages_problem"."title", "pages_problem"."tags" FROM "pages_problem" WHERE "pages_problem"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:24,571 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:24,800 utils (0.015) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:25,022 base Exception while resolving variable 'case' in template 'chat/chat-ai.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'case'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [case] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D43189B20>>, 'request': <ASGIRequest: GET '/chat/ai'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/ai'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'problems': [], 'problems_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: content. Contents: [<TextNode: '\n\n    <section class="py-'>, <IncludeNode: template=<FilterExpression "'message.html'">>, <TextNode: '\n            <div class="'>, <URLNode view_name=''request-ai'' args=[] kwargs={} as=None>, <TextNode: '">New chat</a>\n          '>, <IfNode>, <TextNode: '\n                    </di'>, <IfNode>, <TextNode: '\n                </div>\n '>]>}]
DEBUG 2023-08-22 16:54:25,025 base Exception while resolving variable 'ws_url' in template 'chat/chat-ai.html'.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'ws_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python311\Lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [ws_url] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000012D43189B20>>, 'request': <ASGIRequest: GET '/chat/ai'>, 'user': <SimpleLazyObject: <Account: 1>>, 'perms': PermWrapper(<SimpleLazyObject: <Account: 1>>), 'messages': <FallbackStorage: request=<ASGIRequest: GET '/chat/ai'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'form': None}, {}, {'default_language': True, 'problems': [], 'problems_count': 0, 'DATA_UPLOAD_MAX_MEMORY_SIZE': 10485760, 'current_language': 'bn'}, {'block': <Block Node: script. Contents: [<TextNode: '\n\n    <script src="https:'>, StaticNode(varname=None, path=<FilterExpression '"assets/js/form_handler.js"'>), <TextNode: '"></script>\n\n    <script '>, <Variable Node: ws_url>, <TextNode: '";\n        if (wsURL !== '>, <Variable Node: request.user.id>, <TextNode: '";\n\n                    c'>]>}]
INFO 2023-08-22 16:54:25,028 runserver HTTP GET /chat/ai 200 [3.91, 127.0.0.1:56620]
DEBUG 2023-08-22 16:54:36,823 utils (0.000) QUERY = 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s) LIMIT 21' - PARAMS = (datetime.datetime(2023, 8, 22, 10, 54, 36, 820455), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); args=(datetime.datetime(2023, 8, 22, 10, 54, 36, 820455), 'j468wrupj1wu9ibmmygeidtg5dy3mkrn'); alias=default
DEBUG 2023-08-22 16:54:39,551 utils (0.000) QUERY = 'SELECT "accounts_account"."id", "accounts_account"."date_joined", "accounts_account"."last_login", "accounts_account"."is_superuser", "accounts_account"."is_admin", "accounts_account"."is_staff", "accounts_account"."is_expert", "accounts_account"."is_verified", "accounts_account"."is_active", "accounts_account"."image", "accounts_account"."first_name", "accounts_account"."last_name", "accounts_account"."email", "accounts_account"."phone", "accounts_account"."password", "accounts_account"."reputation" FROM "accounts_account" WHERE "accounts_account"."id" = %s LIMIT 21' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:39,786 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
DEBUG 2023-08-22 16:54:40,007 utils (0.000) QUERY = 'SELECT "accounts_notification"."id", "accounts_notification"."timestamp", "accounts_notification"."account_id", "accounts_notification"."created_by_id", "accounts_notification"."notification", "accounts_notification"."read" FROM "accounts_notification" WHERE "accounts_notification"."account_id" = %s' - PARAMS = (1,); args=(1,); alias=default
INFO 2023-08-22 16:54:40,243 runserver HTTP GET / 200 [3.42, 127.0.0.1:56620]
